title: Greens
status: draft
collated: true
default: green-dark
variants:
  - name: green-dark
    context:
      className: bg-green-dark
      colorName: green-dark
      colorCode: '#2f4d26'
      accessible: true
  - name: green-state
    context:
      className: bg-green-state-hex
      colorName: green-state-hex
      colorCode: '#46653c'
      accessible: true
  - name: green
    context:
      className: bg-green
      colorName: green
      colorCode: '#587f4c'
      accessible: true
  - name: green-land
    context:
      className: bg-green-land
      colorName: green-land
      colorCode: '#69995a'
      accessible: false
  - name: green-mid
    context:
      className: bg-green-mid
      colorName: green-mid
      colorCode: '#9dbd92'
      accessible: false
  - name: green-light
    context:
      className: bg-green-light
      colorName: green-light
      colorCode: '#cde3c3'
      accessible: false
