title: Charts
status: blocked
collated: true
default: Charts
variants:
  - name: Charts
    context:
      className: h3.cart-title
      text: Bar charts
  - name: Mobile-sparkbars
    context:
      className: hide-expanded.chart-title-small
      text: Mobile sparkbar accordions!
