title: US EITI

sass:
  style: compressed
  sass_dir: _sass

exclude:
  - lib
  - node_modules
  - package.json
  - show
  - test
  - 'Gemfile*'

collections:
  communities:
    output: true
    permalink: /communities/:community/
  explores:
    output: true
    permalink: /explores/:explore/
