title: USEITI

description: USEITI is part of an international effort to promote open and accountable management of natural resources. This site provides data about how the U.S. manages extractive industries.

# permanent url, for use in meta references
url: https://useiti.doi.gov

# app version number
version: v1.1.0

sass:
  style: nested
  sass_dir: _sass

exclude:
  - lib
  - node_modules
  - package.json
  - show
  - test
  - styleguide-template
  - 'Gemfile*'

collections:
  case-studies:
    output: true
    permalink: /case-studies/:case-study/
  explore:
    output: true
    permalink: /explore/:explore/
  how-it-works:
    output: true
    permalink: /how-it-works/:subpage/
  downloads:
    output: true
    permalink: /downloads/:subpage/

company_revenue_years:
  - 2013
  - 2014
