title: USEITI

description: USEITI is part of an international effort to promote open and accountable management of natural resources. This site provides data about how the U.S. manages extractive industries.

# permanent url, for use in meta references
url: https://useiti.doi.gov

# app version number
version: v1.2.1

sass:
  style: nested
  sass_dir: _sass

exclude:
  - /*.md
  - kss-config.json
  - lib
  - node_modules
  - npm-debug.log
  - package.json
  - show
  - styleguide-template
  - test
  - webpack.config.js
  - Gemfile*
  # ignore all of the source (unbuilt) JS files
  - js/src
  # shell and other scripts
  - /*.sh
  - /**/bin/*.js
  - /lib/*.js
  - data/lib/*.js
  - maps/lib/*.js
  - /Makefile
  - /**/Makefile
  # data tools and SQLite databases
  - /*.sql
  - /*.db*
  - data/db
  - data/**/*.js
  - data/**/*.svg
  - maps/data

collections:
  case-studies:
    output: true
    permalink: /case-studies/:case-study/
  explore:
    output: true
    permalink: /explore/:explore/
  how-it-works:
    output: true
    permalink: /how-it-works/:subpage/
  downloads:
    output: true
    permalink: /downloads/:subpage/
  federal-revenue-by-company:
    output: true
    permalink: /explore/federal-revenue-by-company/:path/

defaults:
  - scope:
      path: ''
      collection: company-data
    values:
      layout: federal-revenue-by-company

page_gen:
  - data: 'states'
    template: 'state-page'
    name: 'id'
    dir: 'states'
    extension: 'html'

page_gen_dirs: true

shruggie:
  - d8394cf27efbf8ae2f96ee12788eb257f4358a42
