title: US EITI

sass:
  style: compressed
  sass_dir: _sass

exclude:
  - lib
  - node_modules
  - package.json
  - show
  - test
  - styleguide-template
  - 'Gemfile*'

collections:
  case-studies:
    output: true
    permalink: /case-studies/:case-study/
  explores:
    output: true
    permalink: /explores/:explore/
  how-it-works:
    output: true
    permalink: /how-it-works/:subpage/
