name: Natural Resource Revenue from U.S. Federal Lands
description: 'The U.S. earns revenue on natural resources extracted from its lands, a major support for both the country and local municipalities. Find data and information on U.S. extractive industries here.'

owner:
  name: Department of the Interior
  twitter: '@DOIONRR'
  facebook: DOIONRR
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

google_analytics:
google_verify:

logo: '/static/img/U_S__Department_of_the_Interior.gif'

sass:
  sass_dir: static/_sass

markdown: kramdown
highlighter: pygments

gems:
  - jekyll-sitemap

baseurl: /doi-extractives-data

# only use when absolute URL is absolutely necessary
url: https://useiti.doi.gov

kramdown:
  parse_block_html: true

cachebuster: '0426131729'
unilatteral_data: 'CY13_Revenues_by_company_03_18_2015.csv'
exclude: [Gemfile*]
