version: '2'
services:
  base_app:
    build: .
    volumes:
      - .:/doi
      - bundle:/usr/local/bundle/
      - data-shp:/doi/data/shp
      - node-modules:/doi/node_modules
      - patterns-cache:/doi/pattern-library/.cache
      - patterns:/doi/patterns
      - patterns-node-modules:/doi/pattern-library/node_modules
      - patterns-public:/doi/pattern-library/public
      - public:/doi/public
      - root:/root/
      - site:/doi/_site
      - styleguide:/doi/styleguide
    environment:
      - EIA_API_KEY
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
      - CHOKIDAR_USEPOLLING=true
