version: '2'
services:
  jekyll:
    extends:
      file: docker-services.yml
      service: base_app
    command: node scripts/jekyll-watch.js
  webpack:
    extends:
      file: docker-services.yml
      service: base_app
    command: webpack --watch --watch-poll
    stop_signal: SIGKILL
  express:
    extends:
      file: docker-services.yml
      service: base_app
    command: node scripts/dev-server.js
    depends_on:
      - jekyll
      - webpack
    ports:
      - 4000:4000
  styleguide:
    extends:
      file: docker-services.yml
      service: base_app
    command: npm run watch-styleguide
    depends_on:
      - webpack
    ports:
      - 3000:3000
  patterns:
    extends:
      file: docker-services.yml
      service: base_app
    # Use --host because something about how Gatsby listens to the socket on
    # localhost doesn't translate for docker-compose
    command: npm run develop -- --host 0.0.0.0
    working_dir: /doi/pattern-library
    depends_on:
      - webpack
    ports:
      - 8000:8000
volumes:
  root:
  bundle:
  public:
  node-modules:
  patterns:
  patterns-cache:
  patterns-node-modules:
  patterns-public:
