version: '2'
services:
  base_app:
    build: .
    volumes:
      - .:/doi
      - node-modules:/doi/node_modules/
      - root:/root/
      - bundle:/usr/local/bundle/
      - public:/doi/public
    environment:
      - EIA_API_KEY
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
      - CHOKIDAR_USEPOLLING=true
