# units that stay the same
barrels:
  long: barrels
  short: barrels
mcf:
  long: mcf
  short: mcf
tons:
  long: tons
  short: tons
short tons:
  long: short tons
  short: short tons
# oil
bbl:
  long: billions of barrels
  short: bbl
# units of energy
kilowatt hours:
  short: kWh
  long: kilowatt hours
# geothermal energy
electrical generation, thousands of pounds:
  short: klb
  long: thousand pounds
  suffix: energy
  title: electrical generation
direct utilization, millions of btus:
  short: MMBTUs
  long: millions of BTUs
  suffix: energy
  title: direct use
electrical generation, kilowatt hours:
  short: kWh
  long: kilowatt hours
  suffix: energy
  title: electrical generation
electrical generation, other:
  short: units
  long: units
  suffix: energy
  title: electrical generation
direct use, millions of gallons:
  short: Mgal
  long: millions of gallons
  suffix: energy
  title: direct use
direct utilization, hundreds of gallons:
  short: cgal
  long: hundreds of gallons
  suffix: energy
  title: direct use
sulfur:
  short: sulfur
  long: sulfur
  suffix: energy
  title: sulfur
# misc
tickets/pounds:
  short: lbs
  long: tickets/pounds
tons- equivalent:
  short: tons
  long: equivalent tons

