# units that stay the same
mcf:
  long: mcf
  short: mcf
tons:
  long: tons
  short: tons
  term: ton
short tons:
  long: short tons
  short: short tons
  term: short ton
# oil and gas
bbl:
  long: barrels
  short: bbl
  term: barrel
barrels:
  long: barrels
  short: bbl
  term: barrel
gal:
  long: gallons
  short: gal
  term: gallon
# units of energy
kilowatt hours:
  short: kWh
  long: kilowatt hours
  term: kilowatt hour
mwh:
  short: Mwh
  long: megawatt hours
  suffix: energy
  term: megawatt hours
megawatt hours:
  short: Mwh
  long: megawatt hours
  suffix: energy
  term: megawatt hours
# geothermal energy
electrical generation, thousands of pounds:
  short: klb
  long: thousand pounds
  suffix: energy
  title: electrical generation
  term: pound (lb)
direct utilization, millions of btus:
  short: MMBTUs
  long: million BTUs
  suffix: energy
  title: direct use
  term: BTU
electrical generation, kilowatt hours:
  short: kWh
  long: kilowatt hours
  suffix: energy
  title: electrical generation
  term: kilowatt hour
electrical generation, other:
  short: units
  long: units
  suffix: energy
  title: electrical generation
direct use, millions of gallons:
  short: Mgal
  long: million gallons
  suffix: energy
  title: direct use
  term: gallon
direct utilization, hundreds of gallons:
  short: cgal
  long: hundred gallons
  suffix: energy
  title: direct use
  term: gallon
Geothermal - Direct Utilization, Other (cgal):
  short: cgal
  long: hundred gallons
  suffix: energy
  title: direct use
  term: gallon
cgal:
  short: cgal
  long: hundred gallons
  suffix: energy
  title: direct use
  term: gallon
sulfur:
  short: sulfur
  long: sulfur
  suffix: energy
  title: sulfur
# misc
tickets/pounds:
  short: lbs
  long: tickets/pounds
tons- equivalent:
  short: tons
  long: equivalent tons
  term: ton

