title: Breadcrumbs
status: draft
collated: true
default: Breadcrumb
variants:
  - name: Breadcrumb
    context:
      className: breadcrumb
      text: Breadcrumb link /
  - name: Breadcrumb-iconic
    context:
      className: case-studies-content-icon
      text: Breadcrumb link with icon
