title: Black and grays
status: blocked
collated: true
notes: '"Accessible" colors can be used as text fills over white backgrounds, since the contrast ratio between the color and white is at least 4.5:1.'
default: black
variants:
  - name: black
    context:
      className: bg-black
      colorName: black
      colorCode: '#1c2326'
      accessible: true
  - name: black-light
    context:
      className: bg-black-light
      colorName: black-light
      colorCode: '#323c42'
      accessible: true
  - name: gray-darkest
    context:
      className: bg-gray-darkest
      colorName: gray-darkest
      colorCode: '#435159'
      accessible: true
  - name: gray-darker
    context:
      className: bg-gray-darker
      colorName: gray-darker
      colorCode: '#5c737f'
      accessible: true
  - name: gray-dark
    context:
      className: bg-gray-dark
      colorName: gray-dark
      colorCode: '#768d99'
      accessible: false
  - name: gray
    context:
      className: bg-gray
      colorName: gray
      colorCode: '#a7bcc7'
      accessible: false
  - name: gray-light
    context:
      className: bg-gray-light
      colorName: gray-light
      colorCode: '#d3dfe6'
      accessible: false
  - name: gray-lighter
    context:
      className: bg-gray-lighter
      colorName: gray-lighter
      colorCode: '#ebf3f7'
      accessible: false
  - name: gray-pale
    context:
      className: bg-gray-pale
      colorName: gray-pale
      colorCode: '#f0f6fa'
      accessible: false
  - name: white
    context:
      className: bg-white
      colorName: white
      colorCode: '#ffffff'
      accessible: false
