version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.7.0
    steps:
      - checkout
      - restore_cache:
          key: v2-node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: npm install
      - save_cache:
          key: v2-node-modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build gatsby
          command: NODE_OPTIONS=--max_old_space_size=1000 npm run build
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  commit:
    jobs:
      - build
