version: 2

jobs:
  build:
    docker:
      - image: circleci/node:11.7.0
    steps:
      - checkout
      - restore_cache:
          key: v2-node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Setup CF CLI
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
      - run:
          name: Install node dependencies
          command: npm install
      - save_cache:
          key: v2-node-modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build gatsby
          command: NODE_OPTIONS=--max_old_space_size=4096 npm run build
      - run:
          name: Run tests
          command: npm test
  test:
    post:
      - cf login -a https://api.fr.cloud.gov -u DEPLOYER_SERVICE_ACCOUNT_USERNAME -p $CF_PASS -o ORG -s SPACE
  deployment:
    production:
      branch: cloudgov-poc
      commands:
        - cf push
workflows:
  version: 2
  commit:
    jobs:
      - build
      - test
      - deployment
