title: Maps
status: jscomponent
default: Arizona
context:
  container:
    class: container-left-3
variants:
  - name: Arizona
    label: AZ
    context:
      state: AZ
      viewbox: 196 307 141 118

  - name: Alaska
    label: AK
    context:
      state: AK
      viewbox: 49 441 245 115
