title: Maps
status: blocked
collated: true
default: ownership
variants:
  - name: ownership
    context:
      className: TBD
      text: Ownership map
  - name: solid-fill
    context:
      className: TBD
      text: Map with solid-color fill
  - name: others? (county, etc.)
    context:
      className: TBD
      text: More? County? Small?
