title: Button
status: draft
collated: true
default: primary
variants:
  - name: primary
    context:
      className: button-primary
      text: Primary button
  - name: secondary
    context:
      className: button-secondary
      text: Secondary button
  - name: tertiary
    context:
      className: button-tertiary
      text: Tertiary button
  - name: toggle-filter
    context:
      className: toggle-filter
      text: Filter toggle
