title: Accordions
status: draft
collated: true
default: Hide-expanded
variants:
  - name: Hide-expanded
    context:
      className: aria-toggle-icon
      text: Small toggle with icon
  - name: Mobile-sticky-nav
    context:
      className: mobile_nav_header
      text: Mobile sticky-header nav
  - name: Mobile-accordion-panel
    context:
      className: revenues_subpage-steps_group_item
      text: Mobile panel, as seen in Production process
