title: Accordions
status: blocked
default: plus-button
context:
  label: Click to expand accordion
  expandable-content: I'm expanded!
variants:
  - name: plus-button
  - name: in-table
  - name: mobile
    context:
      label: Mobile-collapsing accordion
    display:
      max-width: 599px
  - name: mobile-menu
    context:
      label: Mobile menu
      menu-items:
        - Home
        - About
        - Contribute
    display:
      max-width: 767px
