title: Color palette
status: draft
collated: true
default: black
variants:
  - name: blue
    context:
      className: bg-blue
      text: #1478a6
  - name: black
    context:
      className: bg-black
      text: #1c2326
  - name: black-light
    context:
      className: bg-black-light
      text: #323c42
  - name: gray-darkest
    context:
      className: bg-gray-darkest
      text: #43519
  - name: gray-darker
    context:
      className: bg-gray-darker
      text: #5c7e7f
