title: Typography
status: draft
collated: true
default: h1
variants:
  - name: h1
    context:
      className: h1
      text: h1 header
  - name: h2
    context:
      className: h2
      text: h2 header
  - name: h3
    context:
      className: h3
      text: h3 header
  - name: h4
    context:
      className: h4
      text: h4 header
  - name: h5
    context:
      className: h5
      text: h5 header

  - name: para-xl
    context:
      className: para-xl
      text: This is extra-large text, useful for ...
  - name: para-lg
    context:
      className: para-lg
      text: This is large text, the default size for the site.
  - name: para-md
    context:
      className: para-md
      text: This is medium-sized text.
  - name: para-sm
    context:
      className: para-sm
      text: This is small text, obvi. The type gets even smaller in spots, if you can believe it. Long story.
  - name: more
    context:
      className: p
      text: and .....?
