title: Blues
status: draft
collated: true
default: blue-deep
variants:
  - name: blue-deep
    context:
      className: bg-blue-deep
      colorName: blue-deep
      colorCode: '#00354f'
  - name: blue-darker
    context:
      className: bg-blue-darker
      colorName: blue-darker
      colorCode: '#005078'
  - name: blue-dark
    context:
      className: bg-blue-dark
      colorName: blue-dark
      colorCode: '#086996'
  - name: blue
    context:
      className: bg-blue
      colorName: blue (links)
      colorCode: '#1478a6'
  - name: blue-mid-dark
    context:
      className: bg-blue-mid-dark
      colorName: blue-mid-dark
      colorCode: '#3d95bd'
  - name: blue-mid
    context:
      className: bg-blue-mid
      colorName: blue-mid
      colorCode: '#79bbda'
  - name: blue-cthru
    context:
      className: bg-blue-cthru
      colorName: blue-cthru (filter bg)
      colorCode: 'rgba(198, 233, 255, 0.93)'
  - name: blue-light
    context:
      className: bg-blue-light
      colorName: blue-light
      colorCode: '#dcf4fd'
  - name: blue-lighter
    context:
      className: bg-blue-lighter
      colorName: blue-lighter
      colorCode: '#f2fdff'
