title: Icons
status: draft
collated: true
default:
variants:
  - name: coal
    context:
      className: icon-coal
      text: .icon-coal
  - name: copper
    context:
      className: icon-copper
      text: .icon-copper
  - name: hardrock
    context:
      className: icon-hardrock
      text: .icon-hardrock
  - name: iron
    context:
      className: icon-iron
      text: .icon-iron
  - name: gas
    context:
      className: icon-gas
      text: .icon-gas
  - name: geo
    context:
      className: icon-geo
      text: .icon-geo
  - name: gold
    context:
      className: icon-gold
      text: .icon-gold
  - name: oil
    context:
      className: icon-oil
      text: .icon-oil
  - name: wind
    context:
      className: icon-wind
      text: .icon-wind
  - name: chevron-sm
    context:
      className: icon-chevron-sm
      text: .icon-chevron-sm
  - name: chevron-sm-left
    context:
      className: icon-chevron-sm-left
      text: .icon-chevron-sm-left
  - name: chevron-sm-down
    context:
      className: icon-chevron-sm-down
      text: .icon-chevron-sm-down
  - name: chevron-sm-up
    context:
      className: icon-chevron-sm-up
      text: .icon-chevron-sm-up
  - name: chevron-lg
    context:
      className: icon-chevron-lg
      text: .icon-chevron-lg
  - name: chevron-lg-left
    context:
      className: icon-chevron-lg-left
      text: .icon-chevron-lg-left
  - name: chevron-lg-up
    context:
      className: icon-chevron-lg-up
      text: .icon-chevron-lg-up
  - name: chevron-lg-down
    context:
      className: icon-chevron-lg-down
      text: .icon-chevron-lg-down
  - name: plus-sm
    context:
      className: icon-plus-sm
      text: .icon-plus-sm
  - name: plus-lg
    context:
      className: icon-plus-lg
      text: .icon-plus-lg
  - name: dash-sm
    context:
      className: icon-dash-sm
      text: .icon-dash-sm
  - name: dash-lg
    context:
      className: icon-dash-lg
      text: .icon-dash-lg
  - name: close
    context:
      className: icon-close-x
      text: .icon-close-x
  - name: book
    context:
      className: icon-book
      text: .icon-book
  - name: map
    context:
      className: icon-map
      text: .icon-map
  - name: cloud
    context:
      className: icon-cloud
      text: .icon-cloud
  - name: search
    context:
      className: icon-search
      text: .icon-search
  - name: bars
    context:
      className: icon-bars
      text: .icon-bars
